// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function map(f, optionA) {
  if (optionA !== undefined) {
    return Js_primitive.some(Curry._1(f, Js_primitive.valFromOption(optionA)));
  }
  
}

function map2(f, optionA, optionB) {
  if (optionA !== undefined && optionB !== undefined) {
    return Js_primitive.some(Curry._2(f, Js_primitive.valFromOption(optionA), Js_primitive.valFromOption(optionB)));
  }
  
}

function map3(f, optionA, optionB, optionC) {
  if (optionA !== undefined && optionB !== undefined && optionC !== undefined) {
    return Js_primitive.some(Curry._3(f, Js_primitive.valFromOption(optionA), Js_primitive.valFromOption(optionB), Js_primitive.valFromOption(optionC)));
  }
  
}

function map4(f, optionA, optionB, optionC, optionD) {
  if (optionA !== undefined && optionB !== undefined && optionC !== undefined && optionD !== undefined) {
    return Js_primitive.some(Curry._4(f, Js_primitive.valFromOption(optionA), Js_primitive.valFromOption(optionB), Js_primitive.valFromOption(optionC), Js_primitive.valFromOption(optionD)));
  }
  
}

function map5(f, optionA, optionB, optionC, optionD, optionE) {
  if (optionA !== undefined && optionB !== undefined && optionC !== undefined && optionD !== undefined && optionE !== undefined) {
    return Js_primitive.some(Curry._5(f, Js_primitive.valFromOption(optionA), Js_primitive.valFromOption(optionB), Js_primitive.valFromOption(optionC), Js_primitive.valFromOption(optionD), Js_primitive.valFromOption(optionE)));
  }
  
}

function andThen(f, opt) {
  if (opt !== undefined) {
    return Curry._1(f, Js_primitive.valFromOption(opt));
  }
  
}

function withDefault($$default, opt) {
  if (opt !== undefined) {
    return Js_primitive.valFromOption(opt);
  } else {
    return $$default;
  }
}

exports.map = map;
exports.map2 = map2;
exports.map3 = map3;
exports.map4 = map4;
exports.map5 = map5;
exports.andThen = andThen;
exports.withDefault = withDefault;
/* No side effect */
